export const FETCHING_USER = "FETCHING_USER";
export const USER_FETCHED = "USER_FETCHED";

export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGNING_OUT_USER = "SIGNING_OUT_USER";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOADING_LOCATION = "LOADING_LOCATION";
export const LOCATION_FETCHED = "LOCATION_FETCHED";
export const LOCATION_ERROR = "LOCATION ERROR";

export const FETCHING_ADDRESS = "FETCHING_ADDRESS";
export const ADDRESS_FETCHED  = "ADDRESS_FETCHED"
